language: php

php:
  - 5.5
  - 5.6

services:
  - mysql

sudo: false

env:
  - PHALCON_VERSION="2.1.x"
  - PHALCON_VERSION="2.0.x"
  - PHALCON_VERSION="phalcon-v2.0.8"
  # - PHALCON_VERSION="phalcon-v2.0.7"
  # - PHALCON_VERSION="phalcon-v2.0.6"
  # - PHALCON_VERSION="phalcon-v2.0.1"
  # - PHALCON_VERSION="phalcon-v2.0.0"

before_script:

  # create 'slayer' database
  - mysql -e 'create database slayer charset=utf8mb4 collate=utf8mb4_unicode_ci;'

  # run the composer update
  - travis_retry composer self-update
  - travis_retry composer require phpunit/phpunit=^4.7
  - travis_retry composer require mockery/mockery=^0.9.4
  - travis_retry composer update --prefer-source --no-interaction --prefer-stable

  # copy .env.travis as .env file
  - cp ./vendor/phalconslayer/framework/tests/.env.travis ./.env

  # install  phalcon/cphalcon
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}
  - cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && make install && phpenv config-add ../unit-tests/ci/phalcon.ini
  - php -r 'echo \Phalcon\Version::get()."\n";'
  - cd ../..

  # run the migration and seeder
  - php brood db:migrate
  - php brood db:seed

script:
  - chmod a+x ./vendor/bin/phpunit
  - chmod a+x ./vendor/phalconslayer/framework/phpunit.xml
  - ./vendor/bin/phpunit -c ./vendor/phalconslayer/framework/phpunit.xml
  - php brood db:rollback
